name: Debugging project build

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  debug-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io
            accept-flake-config = true

      - name: Cache Nix
        uses: input-output-hk/actions/attic@8663542d03a41382d97ee344a4e3955280db5f95
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          endpoint: https://attic.ci.iog.io
          cache: midnight-public
          access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - uses: actions/checkout@v4

      - name: Build lib
        run: |
          nix build .#runtime.forPublish

      - name: Install dependencies
        run: |
          cd ./debug-test
          yarn install

      - name: Compile contract
        run: |
          cd ./debug-test
          nix develop .#compiler --command compactc src/contract.compact gen

      - name: Build and test
        run: |
          cd ./debug-test
          yarn build
          yarn test
