name: Build, test and release vscode plugin

on:
  workflow_dispatch:
  push:
    tags:
      - 'compact-vsc-plugin-[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest-8-core-x64
    timeout-minutes: 45
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          #github_access_token: ${{ secrets.MIDNIGHTCI_PACKAGES_READ }}
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io
            accept-flake-config = true

      - name: Cache Nix
        uses: input-output-hk/actions/attic@latest
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          endpoint: https://attic.ci.iog.io
          cache: midnight-public
          access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Checkout compactc repository
        uses: actions/checkout@v4

      - name: Compile
        run: |
          nix build .#compact-vscode-extension

      - name: Upload plugin
        uses: actions/upload-artifact@v4
        with:
          name: compact-vscode-plugin
          path: result/compact-*.vsix

      - name: Extract Version
        run: |
          echo "Full ref name: ${{ github.ref_name }}"
          VERSION=$(echo "${{ github.ref_name }}" | grep -oP '\d+\.\d+\.\d+')
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Use Extracted Version
        run: |
          echo "Version extracted: ${{ env.version }}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          repository: midnight-ntwrk/artifacts
          tag_name: ${{ github.ref_name }}
          name: Compact VSC Plugin ${{ env.version }}
          draft: false
          prerelease: false
          files: result/compact-*.vsix
          token: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
          body: Compact VSC Plugin ${{ env.version }}
